### ISSUE TITLE
Helper c function that returns builtin LED error?

### ISSUE THREAD

**Issue by deanmaniatis** [cesanta/mongoose-os#201]
Hello, got my hands on a new ESP32 dev. board and for some reason the `get_led_gpio_pin()` returns value 21 where in fact it should have returned 2. Is this something to do with esp32 firmware, mongoose API or something different?

**Comment by cpq** [comment]
pin 21 for esp32  is correct.

The thing is , esp32 devkit C board does not have any built-in LED!
that's why we return just a random pin which is close to the GND pin, in order to use an external LED:

![](https://kamami.pl/58840-thickbox_default/esp32-devkitc-plytka-rozwojowa-iot-z-modulem-wi-fi-esp-wroom-32-firmy-espressif.jpg)

**Comment by deanmaniatis** [comment]
This is my board, designed by eboxmaker. The builtin LED is connected to PIN 2. 

![eboxmaker ESP32](https://cloud.githubusercontent.com/assets/7547374/23504384/ddfb3990-ff47-11e6-858e-f144a3afc5c5.jpeg)

**Comment by deanmaniatis** [comment]
@cpq Is it worth implementing profiles for different boards ?

**Comment by cpq** [comment]
Got it, thank you.
profiles, uhh... i think that'll be too much, to be honest..

`let PIN = 2;` would do the job :)
