### ISSUE TITLE
ESP8266: C++: constructors are not invoked for global objects

### ISSUE THREAD

**Issue by rojer** [cesanta/mongoose-os#460]
%subj%

**Comment by WooWapDaBug** [comment]
This code crashed because of this issue:

`
#include <mgos.h>
#include <map>

std::map<int,int> my_map;

extern "C" enum mgos_app_init_result mgos_app_init(void) {

    my_map[0] = 5;

    mgos_set_timer(1000, MGOS_TIMER_REPEAT, [](void*){
        LOG(LL_INFO, ("Test: %i", my_map[0]));
    }, NULL);

    return MGOS_APP_INIT_SUCCESS;
}
`

If anybody runs into this issue, just avoid global complex objects. Just create pointers and initialize them with new in the main init function.

**Comment by WooWapDaBug** [comment]
Why is this closed? is it now solved?

**Comment by rojer** [comment]
@WooWapDaBug it's been fixed, but commits are not published immediately. they are now (see above).
